apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-out-to-in
  namespace: default
spec:
  podSelector: 
    matchLabels:
     app: mongo-pod
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: node-pod
  egress:
  policyTypes:
  - Ingress
  - Egress
