---
  - hosts: webservers
    gather_facts: no
    remote_user: ec2-user
    become: true
    become_method: sudo
    become_user: root
    tasks:
  #tasks file for httpdserver
     - command: curl http://ipv4.icanhazip.com
       register: x
     - name: install httpd
       package:
           name: httpd
           state: present
       register: status
     - name: install php
       package:
           name: php
           state: present
     - name: configure httpd
       template:
           src: my.conf
           dest: /etc/httpd/conf.d/my.conf
       when: status.rc == 0
       notify: restart httpd
