---
  # tasks file for httpdserver
  #- name: Run the equivalent of "apt-get update"
    # shell: apt-get update -y && apt-get autoremove && apt-get autoclean
     - name: install httpd
       package:
           name: httpd
           state: present
       register: status
     - name: install php
       package:
           name: php
           state: present
     - name: configure httpd
       template:
           src: my.conf
           dest: /etc/httpd/conf.d/my.conf
       when: status.rc == 0
       #notify: restart httpd
